name: cnn
init:
  enable: true
  #entity: "zizi-Deep-Learning-Labor"
  project: NEW_human_activity  #_cnn_transformer
  name: "${save.date_prefix}_${model.name}"
  group: experiment_hapt_cnn_transformer
  tags: [HAPT,CNN,TRANSFORMER]
  id: null