name: HAPT
path: /home/data/HAPT_dataset/RawData      



train_users: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
val_users: [28,29,30]
test_users: [22,23,24,25,26,27]  

#in+channel: 11
mean: [ 0.8157596,-0.02046478,0.06585141,0.0241855,-0.0103994,-0.00881192,1.0346466,0.521194,2.2967138,-1.0481449,-0.72582126]
std: [0.39320713,0.3862467,0.36073887,0.5897387,0.46612737,0.36069915,0.19173154,0.65120965,4.0965943,0.48016655,1.5826256 ]
eps: 1e-8


batch_size: 32
num_workers: 4

sliding_window:
  window_size: 128 #128-64 64-32
  window_shift: 64 #
  label_mode: "majority"  #"center" # "majority" # "center" 